language: node_js
sudo: false
node_js:
- 4.2.1
env:
  global:
  - LOG_LEVEL_STDOUT=error
cache:
- directories:
  - ./node_modules
services:
- mongodb
- rabbitmq
before_install:
- npm install -g npm@2.14.7
script:
- npm run test
notifications:
  email: false